// Item bank. Y = your sentence (session date), N = new context, X = fix-my-sentence (your sentence).
// Answers: "a|b" = all accepted, "∅" = no preposition. w = this item's own distractors.
function Y(d,t,a,w,n){return{s:'y',d,t,a,w,n};}
function N(t,a,w,n){return{s:'n',t,a,w,n};}
function X(d,t,a,bad,good){return{s:'y',d,x:true,t,a,bad,good};}
const BANK=[
// ---------- Prepositions ----------
{k:'of_not_for',sec:'prep',label:'knowledge / example / chances of',tr:'için (… için bilgim)',wrong:['for','about','to'],
 trap:'Turkish için pulls you towards "for". Which word links a noun like knowledge or example to its topic?',
 why:'Nouns of knowing, showing and likelihood take "of": knowledge of, awareness of, an example of, a test of, the chances of + -ing.',
 items:[Y('06.10','I need to increase my knowledge ___ them.','of'),Y('03.10','That’s a good example ___ "had better".','of'),
 Y('03.10','I’m slowly building my awareness ___ it.','of'),Y('27.09','What are the chances ___ getting this deal?','of'),
 Y('06.10','There’s not much chance ___ eating out tonight.','of'),Y('02.10','That’s a real test ___ my memory.','of'),
 N('Her knowledge ___ Turkish history surprised everyone.','of')]},
{k:'no_prep_verbs',sec:'prep',label:'join / contact / message (no "to")',tr:'dative -e / ile (arkadaşlarına katılmak, benimle iletişime geçmek)',wrong:['to','with'],
 trap:'Turkish marks this object with -e or ile. Does the English verb take its object directly?',
 why:'Join, contact, message, approach and continue take a direct object: join her friends, contact me, message Francesca. "Reply" is the exception: reply to someone.',
 items:[Y('06.10','Yaz wants to join ___ her friends.','∅'),Y('01.10','He still contacts ___ me every week.','∅'),
 Y('29.09','I messaged ___ Francesca last night.','∅'),Y('22.09','There was a car approaching ___ us.','∅'),
 Y('06.10','Let’s continue ___ this lovely chat.','∅|with',['to']),Y('06.10','I replied ___ him straight away.','to',['∅','with'],'"Reply" is the one that needs "to".'),
 N('You can contact ___ the hotel directly.','∅'),X('01.10','There’s no point in contacting to me.','There’s no point in contacting me.|There\'s no point in contacting me.','contacting to me','contacting me')]},
{k:'add_to',sec:'prep',label:'add / save to (not "into")',tr:'listeme eklemek (dative -e)',wrong:['into','in'],
 trap:'Turkish -e (listeme) feels like "into". Is anything physically moving inside?',
 why:'"Add" and "save" take "to": add it to my list, save it to your memory. "Into" is for movement inside a space: put the box into the car.',
 items:[Y('06.10','Can you add them ___ my list?','to'),Y('06.10','I added the quiz work ___ my pipeline.','to'),
 Y('03.10','Please add them ___ your notes.','to'),Y('01.10','Save this ___ your memory.','to'),
 Y('02.10','Let’s add new categories ___ the naturalness check.','to'),N('I’ve added two new columns ___ the spreadsheet.','to'),
 X('18.09','I have already added it into my list.','I have already added it to my list.|I\'ve already added it to my list.','into my list','to my list')]},
{k:'on_my_list',sec:'prep',label:'on my list',tr:'listemde (locative -de)',wrong:['in'],
 trap:'Turkish says listemde (-de, "in"). How do items sit on a list in English?',
 why:'Items are on a list, on the agenda, on the menu. Think of the list as a surface.',
 items:[Y('06.10','That one is already ___ my list.','on'),Y('02.10','Is there another one ___ our list?','on'),
 Y('02.10','Let’s keep it ___ the list.','on'),Y('24.09','I’ve got 40 items ___ my list.','on'),N('What is next ___ the agenda?','on')]},
{k:'include_in',sec:'prep',label:'include in / involved in',tr:'dahil etmek / dahil olmak (dative -e)',wrong:['into'],
 trap:'Turkish -e (analize dahil etmek) suggests movement. English treats this as being inside.',
 why:'"Include" and "involved" take "in": include it in the analysis, be involved in a process, put him back in the loop.',
 items:[Y('01.10','Can you include it ___ your analysis?','in'),Y('01.10','Include them ___ the statistics.','in'),
 Y('28.09','I will be involved ___ the selection process.','in'),Y('01.10','I put him back ___ the loop.','in'),N('Breakfast is included ___ the price.','in')]},
{k:'move_on_to',sec:'prep',label:'move on to',tr:'konuya geçmek (dative -e)',wrong:['into','onto'],
 trap:'Changing topic is a phrasal verb plus a preposition. Two words.',
 why:'To change topic, "move on to" the next point. "Move into" means entering a place, like a new flat.',
 items:[Y('06.10','Before moving ___ that one, I have a question.','on to'),Y('01.10','Let me move ___ my story.','on to'),
 Y('01.10','Moving ___ the next point.','on to'),N('Shall we move ___ the second question?','on to')]},
{k:'dedicate_to',sec:'prep',label:'committed / dedicated to',tr:'kendini bir şeye adamak (dative -e)',wrong:['into','on'],thin:true,
 trap:'Commitment words all share one preposition.',
 why:'Commitment words take "to": committed to, dedicated to, devoted to. A verb after them takes -ing: committed to improving.',
 items:[Y('02.10','You’re dedicating yourself ___ something.','to'),Y('22.09','I will do my best to stay committed ___ this.','to'),
 Y('24.09','This session is dedicated ___ phrasal verbs only.','to'),N('She’s committed ___ improving her speaking.','to')]},
{k:'these_days',sec:'prep',label:'these days (no "in")',tr:'bu günlerde',wrong:['in','at'],
 trap:'"Bu günlerde" has -de. Does "these days" need any preposition?',
 why:'"These days", "this week", "this morning" need no preposition. "In these days" copies "bu günlerde" word for word.',
 items:[Y('24.09','I feel less fluent ___ these days.','∅'),Y('28.09','I want to increase my automaticity ___ these days.','∅'),
 Y('02.10','___ these days, it’s a well-known fact.','∅'),N('Prices are rising fast ___ these days.','∅'),
 Y('05.10','It all started back ___ those days.','in',['at','∅'],'"In those days" (the past) is correct. Only "these days" drops the preposition.')]},
{k:'over_time',sec:'prep',label:'over time',tr:'zamanla',wrong:['in','with'],
 trap:'"Zamanla" describes gradual change. "In time" means something else in English.',
 why:'Gradual change happens "over time". "In time" means early enough (in time for the meeting) or eventually.',
 items:[Y('05.10','Things have changed ___ time.','over'),Y('28.09','The habit just faded away ___ time.','over'),
 Y('28.09','It clicked ___ time.','over'),Y('29.09','It gets tedious ___ time.','over'),
 N('Don’t worry, we will get there ___ time for the meeting.','in',['over'],'Here it means early enough: "in time for".')]},
{k:'weekends',sec:'prep',label:'at / on weekends',tr:'hafta sonlarında (locative -de)',wrong:['in'],
 trap:'"Hafta sonlarında" has -de, which feels like "in". Weekends behave like days.',
 why:'British English says "at the weekend / at weekends", American English "on the weekend / on weekends". Both are right; "in the weekends" is not.',
 items:[Y('03.10','I do my shadowing ___ weekends.','at|on'),Y('20.09','I practise for about 30 minutes ___ weekends.','at|on'),
 Y('25.09','I’m in a good mood ___ most weekends.','on'),N('What are you doing ___ the weekend?','at|on|over'),
 Y('05.10','We will link this national holiday ___ the weekend.','to',['towards','into'],'"Link X to Y" joins two things.')]},
{k:'dates_times',sec:'prep',label:'on + day/date, at + clock time',tr:'27 Ekim\'de / 5:30\'da (-de covers at, on, in)',wrong:['in','at','on'],
 trap:'Turkish -de covers at, on and in. Is this a day, a date, or a clock time?',
 why:'Days and dates take "on" (on Saturday, on 27 October), clock times take "at" (at 5:30), parts of the day take "in" (in the morning), except "at night".',
 items:[Y('05.10','As I mentioned ___ Saturday, we are flying to Abu Dhabi.','on'),Y('05.10','We’re heading to Abu Dhabi ___ 27 October.','on'),
 Y('29.09','The lesson will start ___ 5:30.','at'),Y('01.10','As usual ___ Fridays, the office was quiet.','on'),
 Y('05.10','We fly back ___ the night of the same day.','on'),Y('29.09','I usually cannot sleep ___ night.','at'),
 Y('01.10','It was hard to focus ___ such a busy day.','on'),N('Her birthday is ___ 1 October.','on')]},
{k:'begin_lastmin',sec:'prep',label:'at the beginning / at the last minute',tr:'oturumun başında / son dakikada (-de)',wrong:['in','for'],
 trap:'Turkish -de (başında) pulls in "in". Is this a point in time?',
 why:'A point in time takes "at": at the beginning of the session, at the last minute, at the end. "In the middle of" is the exception.',
 items:[Y('06.10','The change arrived ___ the last minute.','at'),Y('01.10','I made the same mistake ___ the beginning of our conversation.','at'),
 Y('23.09','We talked about it ___ the beginning of this session.','at'),Y('01.10','I’m always tired ___ the middle of the day.','in',['at']),
 N('Sign your name ___ the end of the page.','at')]},
{k:'time_duration',sec:'prep',label:'for + length of time',tr:'iki gündür / 20 dakika (no postposition)',wrong:['since','∅'],thin:true,
 trap:'Is this a length of time, or a starting point?',
 why:'"For" goes with a length of time (for two days, for 20 minutes). "Since" needs a starting point (since Monday, since last night).',
 items:[Y('03.10','She’s been ill ___ two days.','for',['since']),Y('27.09','We have been talking ___ about 20 minutes.','for',['∅','around']),
 Y('03.10','She’s been ill ___ last night.','since',['for'])]},
{k:'sense_of',sec:'prep',label:'a sense of / benefits of / wrong with',tr:'hakkında',wrong:['about'],
 trap:'"Hakkında" pulls in "about". These nouns have their own fixed partner.',
 why:'These nouns take "of": a sense of, the benefits of, an assessment of, the cost of. A fault is "wrong with" something.',
 items:[Y('05.10','This gives you a general sense ___ it.','of'),Y('23.09','I want to get a sense ___ my needs.','of'),
 Y('22.09','What are the benefits ___ the investment?','of'),Y('23.09','I would like your honest assessment ___ the timeline.','of'),
 Y('24.09','Is there something wrong ___ it?','with',['about','of']),N('Do you know the cost ___ the trip?','of')]},
{k:'confused_about',sec:'prep',label:'confused / indecisive about',tr:'bu konuda / konusunda',wrong:['on','for'],
 trap:'"Bu konuda" sounds like "on this". Feelings towards a topic use another word.',
 why:'Feelings and attitudes towards a topic take "about": confused about, enthusiastic about, indecisive about, nervous about.',
 items:[Y('28.09','I’m a bit confused ___ this one.','about'),Y('03.10','She’s indecisive ___ almost everything.','about'),
 Y('24.09','I’m really enthusiastic ___ this topic.','about'),Y('25.09','People are compulsive ___ scrolling.','about'),
 Y('05.10','I feel a bit tense ___ speaking.','about'),N('He’s very nervous ___ the interview.','about')]},
{k:'same_about',sec:'prep',label:'say the same about',tr:'… için de aynısı',wrong:['for'],
 trap:'"X için de aynısı" gives "for". After "say the same", what do we use?',
 why:'"I can say the same about X." The other fixed phrase, "the same goes for X", does use "for".',
 items:[Y('05.10','I can say the same ___ my family.','about'),Y('25.09','I can’t say the same ___ myself.','about'),
 Y('20.09','I can say the same ___ Francesca too.','about'),N('The same goes ___ the other children.','for',['about'],'"The same goes for" is its own fixed phrase.')]},
{k:'same_as',sec:'prep',label:'the same as',tr:'ile aynı',wrong:['with'],
 trap:'"Ile aynı" gives "with". "The same" has a fixed partner.',
 why:'"The same" is followed by "as": the same number as Luke, the same crew as last time.',
 items:[Y('06.10','It’s the same crew ___ on the Dubai trip.','as'),Y('18.09','You have the same lucky number ___ Luke.','as'),
 Y('28.09','Use the same layout ___ the phrasal verb tracker.','as'),N('My answer is the same ___ yours.','as')]},
{k:'for_me',sec:'prep',label:'hard / safer / better for me',tr:'bana / benim için',wrong:['to'],
 trap:'"Bana" (-e) pulls in "to". After an adjective, who is affected?',
 why:'After an adjective, the person affected usually takes "for": hard for me, safer for me, better for you. Some adjectives take "to" (unclear to you, new to me), and "okay with you" asks for agreement.',
 items:[Y('18.09','It’s hard ___ me to pronounce.','for'),Y('30.09','That’s safer ___ me.','for'),
 Y('03.10','It’s better ___ you to record them.','for'),Y('03.10','It’s a tradition ___ us.','for'),
 Y('02.10','Is that okay ___ you?','with',['for']),Y('01.10','Is it unclear ___ you?','to',['for'])]},
{k:'ask_sb_q',sec:'prep',label:'ask someone / share with you',tr:'ona soru sormak / sana paylaşmak (dative -e)',wrong:['to'],
 trap:'Turkish -e (sana) pulls in "to". Where does the person go after "ask"?',
 why:'"Ask" puts the person straight after it: ask her this question. "Share" needs "with": share it with you. A question is "for" someone.',
 items:[X('01.10','Let me ask my question to you.','Let me ask you my question.|Let me ask you a question.','my question to you','you my question'),
 X('29.09','I didn’t ask the same question to my wife.','I didn’t ask my wife the same question.|I didn\'t ask my wife the same question.','the same question to my wife','my wife the same question'),
 Y('05.10','Let me share my signature image ___ you.','with',['to','∅']),Y('23.09','They don’t share their budget figures ___ us.','with',['to']),
 Y('25.09','I have one last question ___ you.','for',['to'])]},
{k:'no_point_in',sec:'prep',label:'no point in + -ing',tr:'… için anlamı yok',wrong:['for','to'],
 trap:'"… için anlamı yok" gives "for". The -ing form after "no point" follows another word.',
 why:'"There is no point in doing something." The -ing form follows "in".',
 items:[Y('30.09','There’s no point ___ discussing it.','in'),Y('28.09','There’s no point ___ complaining.','in'),
 Y('24.09','There’s no point ___ dwelling on it.','in'),N('There’s no point ___ waiting any longer.','in'),
 X('05.10','There’s no point to play with it.','There’s no point in playing with it.|There is no point in playing it.|There\'s no point in playing with it.','to play','in playing')]},
{k:'mention_discuss',sec:'prep',label:'mention / discuss (no "about")',tr:'hakkında bahsetmek / tartışmak',wrong:['about'],
 trap:'"Hakkında" pulls in "about". Does this verb take its object directly?',
 why:'Mention, discuss and research take a direct object: mention the trip, discuss it, research the topic. "Talk about" does take "about"; "refer" needs "to".',
 items:[Y('29.09','I mentioned ___ the Spain trip yesterday.','∅'),Y('23.09','We will discuss ___ it tomorrow.','∅'),
 Y('28.09','He researched ___ the topic.','∅'),N('We talked ___ it for an hour.','about',['∅']),
 Y('30.09','That’s what I was referring ___.','to',['∅'],'"Refer" is the opposite case: it needs "to".')]},
{k:'rooted_in',sec:'prep',label:'rooted in / based on',tr:'-e dayanmak / -den kaynaklanmak',wrong:['to','on','from'],
 trap:'Turkish -e dayanmak gives "to", -den kaynaklanmak gives "from". Roots grow in soil.',
 why:'"Rooted in", "based on", "stems from". Only "stems from" keeps the Turkish "from".',
 items:[Y('23.09','Maybe it is rooted ___ her character.','in'),Y('22.09','It’s rooted ___ a board decision.','in'),
 Y('22.09','This plan isn’t based ___ anything.','on',['to']),Y('24.09','The problem stems ___ poor planning.','from',['by']),
 N('Her fear is rooted ___ her childhood.','in')]},
{k:'responsible_for',sec:'prep',label:'responsible for',tr:'-den sorumlu',wrong:['from'],thin:true,
 trap:'"-den sorumlu" gives "from".',
 why:'"Responsible for something." A decision is "up to" someone.',
 items:[Y('22.09','My department is responsible ___ this process.','for'),Y('22.09','Who is responsible ___ the investment activities?','for'),
 Y('01.10','That decision will be up ___ our management office.','to',['on']),N('Parents are responsible ___ their children\'s safety.','for')]},
{k:'against',sec:'prep',label:'against (no "to")',tr:'-e karşı',wrong:['to'],thin:true,
 trap:'"-e karşı" adds a dative. "Against" is already a preposition.',
 why:'"Against" is itself a preposition, so nothing follows it: against him, against me.',
 items:[Y('22.09','They constantly vote against ___ him.','∅'),Y('22.09','Don’t use it against ___ me.','∅'),
 Y('22.09','This was meant to protect me ___ our old CEO.','from',['against to'])]},
{k:'seek_chase',sec:'prep',label:'seek / chase (no "for")',tr:'peşinde / … için',wrong:['for'],
 trap:'"Look for" has "for". Do "seek" and "chase" need it?',
 why:'"Seek" and "chase" take a direct object: seek a solution, chase big yields. "Look for" and "search for" do take "for".',
 items:[Y('02.10','They’re seeking ___ a solution.','∅'),Y('23.09','They were just chasing ___ big yields.','∅'),
 Y('03.10','I was chasing ___ a meaning.','∅'),N('We’re looking ___ a new flat.','for',['∅'])]},
{k:'invest_in',sec:'prep',label:'put effort into / invest in',tr:'emek vermek / -e yatırmak',wrong:['on','to'],
 trap:'"Üzerine emek vermek" gives "on". Where does effort go?',
 why:'Effort, time and money go "into" something: put effort into it, put savings into a fund. You "invest in" something. Without an object: "put in a lot of effort".',
 items:[Y('30.09','I put a lot of effort and time ___ it.','into'),Y('02.10','He put all his savings ___ that fund.','into'),
 Y('25.09','You need to invest ___ it.','in',['∅']),Y('02.10','They invested ___ this fund.','in',['∅']),
 Y('05.10','We put ___ a lot of effort, as I said before.','in',['∅'],'"Put in effort" with no object after it uses "in".'),N('She put a lot of work ___ this project.','into')]},
{k:'swap_for',sec:'prep',label:'swap X for Y',tr:'X\'i Y ile değiştirmek',wrong:['with','over'],
 trap:'"Ile değiştirmek" gives "with". You give X and get Y.',
 why:'"Swap X for Y" and "trade X for Y": you give X and get Y. "Replace X with Y" is the one that uses "with".',
 items:[Y('03.10','She swapped horse riding ___ gymnastics.','for'),Y('01.10','You’re trading fluency ___ accuracy.','for'),
 Y('28.09','Can we replace it ___ the core-list indicator?','with',['over','for']),N('I swapped my old phone ___ a newer model.','for')]},
{k:'limit_to',sec:'prep',label:'limit it to',tr:'ile sınırlamak',wrong:['with','for'],
 trap:'"Ile sınırlamak" gives "with". What marks the maximum?',
 why:'"Limit something to an amount": limit it to 10. "There is a limit to that" also takes "to".',
 items:[Y('06.10','Let’s limit it ___ 10.','to'),Y('22.09','I will limit it ___ twice a week.','to'),
 Y('05.10','We can limit it ___ a few days.','to'),Y('03.10','There’s a limit ___ that.','to')]},
{k:'key_to',sec:'prep',label:'the key / answer to',tr:'başarı için anahtar / sorunun cevabı',wrong:['for'],
 trap:'"Için" gives "for". Keys fit into locks.',
 why:'"The key to success", "the answer to your question", "a solution to a problem" all take "to".',
 items:[Y('30.09','Practice is the key ___ success.','to'),Y('05.10','Here’s the answer ___ your question.','to'),
 Y('01.10','Regular practice is the key ___ that.','to'),N('Is there a solution ___ this problem?','to')]},
{k:'leave_out_of',sec:'prep',label:'leave X out of',tr:'dışında tutmak / kenarda tutmak',wrong:['out from','apart from'],
 trap:'"Dışında tutmak" suggests "out from". English uses a fixed two-word pair.',
 why:'To exclude something: "leave it out of the analysis". It is "out of", never "out from". "Set aside" means put off for later.',
 items:[Y('01.10','Please leave it ___ your analysis.','out of'),Y('30.09','Leave these words ___ the analysis.','out of'),
 Y('28.09','I couldn’t get ___ this selection process.','out of'),Y('20.09','Let’s set the divorce decision ___ for now.','aside',['out','apart']),
 N('They left my name ___ the report.','out of')]},
{k:'on_device',sec:'prep',label:'on Instagram / on my computer',tr:'Instagram\'da / bilgisayarımda (-de)',wrong:['in','at'],
 trap:'Turkish -de gives "in". Screens and apps behave like surfaces.',
 why:'Apps, websites, devices and screens take "on": on Instagram, on my computer, on the Switch. Islands take "on" too, and so does "on my end".',
 items:[Y('06.10','She plays sports games ___ the Nintendo Switch.','on'),Y('05.10','We will visit the theme parks ___ Yas Island.','on'),
 Y('25.09','I saw it ___ Instagram.','on'),Y('18.09','The files are saved ___ my computer.','on'),
 Y('18.09','Everything is fine ___ my end.','on',['at']),N('I read the news ___ my phone.','on')]},
{k:'on_trip_leave',sec:'prep',label:'on a trip / on leave',tr:'bu seyahatte / yıllık izinde (-de)',wrong:['in'],
 trap:'Turkish -de (seyahatte) gives "in". Trips and leave take another word.',
 why:'Trips, holidays, leave and trial take "on": on a business trip, on annual leave, on trial.',
 items:[Y('29.09','My colleague will accompany me ___ this business trip.','on'),Y('22.09','Everyone was ___ annual leave.','on'),
 Y('02.10','He’s never been ___ trial.','on'),N('They met ___ holiday in Spain.','on')]},
{k:'angry_with',sec:'prep',label:'angry with / mad at / close to',tr:'birine kızgın (-e) / -den sıkılmak',wrong:['to','from'],
 trap:'Turkish -e (kızgın) and -den (sıkılmak) pull in "to" and "from". Each adjective has its own partner.',
 why:'Feelings towards a person: angry with, mad at, bored with (or of), bothered by. Closeness: close to.',
 items:[Y('01.10','We were angry ___ each other.','with',['to']),Y('02.10','I’m getting mad ___ you.','at',['with']),
 Y('22.09','I’m bored ___ this topic.','with|of',['from']),Y('03.10','We’re very close ___ them.','to',['with']),
 Y('29.09','I was bothered ___ this move.','by',['from'])]},
{k:'good_at',sec:'prep',label:'good at / better at',tr:'o konuda / badmintonda (-de)',wrong:['in','on'],thin:true,
 trap:'"O konuda" gives "on", "badmintonda" gives "in". Skills use another word.',
 why:'Skills take "at": good at badminton, better at it, not as good as me at it.',
 items:[Y('06.10','She’s better ___ badminton.','at'),Y('06.10','She’s not that good ___ it.','at'),
 Y('06.10','She’s not as good as me ___ it.','at'),N('My son is really good ___ maths.','at')]},
{k:'save_for',sec:'prep',label:'save it for tomorrow',tr:'yarına saklamak (dative -e)',wrong:['to'],
 trap:'"Yarına" (-e) gives "to". Keeping something for later uses another word.',
 why:'Keeping something for later takes "for": save it for tomorrow, keep this one for another round.',
 items:[Y('22.09','Maybe I can save it ___ tomorrow.','for'),Y('01.10','Let’s save "unfold" ___ another round.','for'),
 Y('02.10','Let’s keep this one ___ another round.','for'),N('I’m saving this wine ___ a special day.','for')]},
{k:'remind_of',sec:'prep',label:'remind someone of',tr:'bana … hatırlattı',wrong:['∅'],
 trap:'"Hatırlatmak" takes a plain object, so the English word disappears. Which word does English need?',
 why:'"Remind someone of something." "Remind someone to do something" is a different pattern.',
 items:[Y('30.09','It reminded me ___ something else.','of'),Y('18.09','Let me remind you ___ the basics first.','of'),
 Y('29.09','Can you remind me ___ the meaning of "bounds"?','of'),N('Remind me ___ call her tomorrow.','to',['of'],'"Remind someone to do" is the other pattern.')]},
{k:'been_to',sec:'prep',label:'have been to',tr:'Dubai\'de bulundum (-de)',wrong:['in'],thin:true,
 trap:'"Dubai\'de bulundum" has -de. Visiting uses another word.',
 why:'For visits, "have been to": I have been to Dubai. "Been in" means you stayed there for a period.',
 items:[Y('25.09','I’ve been ___ Dubai.','to'),Y('25.09','We’ve been ___ Singapore.','to'),
 Y('25.09','I’ve been ___ almost all European countries.','to'),N('Have you ever been ___ Japan?','to')]},
{k:'specific_to',sec:'prep',label:'specific to / applies to',tr:'için',wrong:['for'],thin:true,
 trap:'"Için" gives "for".',why:'"Specific to" something, and "applies to" something.',
 items:[Y('23.09','This rule is specific ___ the filtering.','to'),Y('02.10','This mostly applies ___ the ledger update.','to'),N('These problems are specific ___ large companies.','to')]},
{k:'pace_at',sec:'prep',label:'at a pace',tr:'doğal bir hızla (-le) / hızda (-de)',wrong:['with','in'],thin:true,
 trap:'Turkish -le gives "with", -de gives "in". Speed uses another word.',why:'Speed takes "at": at a natural pace, at 100 km/h.',
 items:[Y('23.09','They speak ___ a natural pace.','at'),Y('23.09','I’m not speaking ___ the pace I want.','at'),N('Prices are rising ___ a worrying pace.','at')]},
{k:'superior_to',sec:'prep',label:'superior to',tr:'-den üstün',wrong:['than'],thin:true,
 trap:'"-den üstün" looks like a comparison, but "superior" is not a comparative form.',why:'"Superior", "inferior" and "prefer" take "to", not "than".',
 items:[Y('22.09','This one is superior ___ the others.','to'),N('The new model is far superior ___ the old one.','to')]},
{k:'different_from',sec:'prep',label:'different from',tr:'no Turkish source recorded',wrong:['than'],thin:true,
 trap:'The safest standard form uses a "from" idea.',why:'"Different from" is the safe standard form; "different to" is British. "Different than" is common in American speech but often marked in exams.',
 items:[Y('01.10','They’re so different ___ each other.','from|to'),Y('01.10','The smoke isn’t so different ___ steam.','from|to')]},
{k:'accused_of',sec:'prep',label:'accused of + -ing',tr:'bir şey yapmakla suçlanmak (-la)',wrong:['by','with'],thin:true,
 trap:'"-la suçlanmak" gives "with" or "by". The crime takes another word.',why:'"Accused of something" or "accused of doing something". "By" names the accuser.',
 items:[Y('02.10','You might get accused ___ doing something.','of'),Y('01.10','He was accused ___ betrayal.','of'),N('She was accused ___ lying.','of')]},
{k:'get_used_to',sec:'prep',label:'get used to',tr:'ile (alışmak)',wrong:['with'],thin:true,
 trap:'"Ile" gives "with".',why:'"Get used to something" or "get used to doing something".',
 items:[Y('06.10','She needs to get used ___ wearing the plate.','to'),N('I’m getting used ___ waking up early.','to')]},
{k:'worth_ing',sec:'prep',label:'worth + -ing',tr:'bilmeye değer (-meye)',wrong:[],thin:true,
 trap:'"-meye değer" pulls in "to". What form follows "worth"?',why:'"Worth" is followed by -ing: worth knowing, worth flagging, worth watching.',
 items:[Y('06.10','The difference wasn’t worth ___ (flag).','flagging',['to flag']),Y('06.10','They’re worth ___ (know).','knowing',['to know']),N('The film is worth ___ (watch).','watching',['to watch'])]},
{k:'short_on_time',sec:'prep',label:'short on time',tr:'no Turkish source recorded',wrong:['in'],thin:true,
 trap:'Lacking something uses a surface word.',why:'"Short on time" or "short on money" means you do not have enough.',
 items:[Y('06.10','She’s always short ___ time.','on'),N('We’re a bit short ___ money this month.','on')]},
{k:'congratulate_on',sec:'prep',label:'congratulate someone on',tr:'için (tebrik etmek)',wrong:['for'],thin:true,
 trap:'"Için" gives "for".',why:'"Congratulate someone on something", and "congratulations on your new job".',
 items:[Y('06.10','I congratulated him ___ his courage.','on'),N('Congratulations ___ your new job!','on')]},
{k:'scene',sec:'prep',label:'come onto the scene',tr:'sahneye (dative -e)',wrong:['into'],thin:true,
 trap:'"Sahneye" (-e) feels like "into". A scene is a surface you appear on.',why:'"Come onto the scene" or "arrive on the scene".',
 items:[Y('06.10','Then a new player came ___ the scene.','onto|on'),N('The police arrived ___ the scene quickly.','on')]},
{k:'help_with',sec:'prep',label:'help someone with',tr:'için / bu konuda',wrong:['for','on'],thin:true,
 trap:'"Için" gives "for", "bu konuda" gives "on".',why:'"Help someone with something": help me with shadowing.',
 items:[Y('06.10','Can you help me ___ shadowing?','with'),Y('05.10','Maybe you could help me ___ that.','with'),N('Can you help me ___ my bags?','with')]},
{k:'wait_for',sec:'prep',label:'wait for',tr:'onu bekliyorum (accusative)',wrong:['∅'],thin:true,
 trap:'"Onu bekliyorum" takes a plain object. English needs a word.',why:'"Wait for someone" and "wait for someone to do something".',
 items:[Y('03.10','I’m waiting ___ her to come out.','for'),N('We’re waiting ___ the bus.','for')]},
{k:'insist_on',sec:'prep',label:'insist on',tr:'-e ısrar etmek (dative -e)',wrong:['to'],thin:true,
 trap:'"-e ısrar etmek" gives "to".',why:'"Insist on something" and "insistent on something"; a verb after it takes -ing.',
 items:[Y('27.09','The landlord is insistent ___ a minimum rent.','on'),N('She insisted ___ paying the bill.','on')]},
{k:'resonate_with',sec:'prep',label:'resonate with',tr:'sana hitap etmek (dative -e)',wrong:['∅','on'],thin:true,
 trap:'"Sana hitap etmek" takes -e. English needs a partner word.',why:'"Something resonates with you" and "how does that land with you?".',
 items:[Y('28.09','It might resonate ___ you.','with'),Y('28.09','How does that land ___ you?','with')]},
{k:'paste_into',sec:'prep',label:'paste into',tr:'sohbete yapıştırmak (dative -e)',wrong:['to'],thin:true,
 trap:'"Sohbete" (-e) gives "to".',why:'You "paste into" a chat, a document or a box.',
 items:[Y('30.09','Paste it ___ our chat.','into'),N('Paste the link ___ the search box.','into')]},
{k:'come_across_as',sec:'prep',label:'come across as',tr:'no Turkish source recorded',wrong:['that'],thin:true,
 trap:'This phrasal verb has a fixed word before the impression.',why:'"Come across as pushy", "come across as rushing", or "come across as if I’m rushing".',
 items:[Y('24.09','I don’t want to come across ___ if I’m rushing.','as'),Y('01.10','I don’t want to come across ___ pushy.','as')]},
{k:'by_using',sec:'prep',label:'by + -ing (method)',tr:'kullanarak (-arak)',wrong:['with','through'],thin:true,
 trap:'"-arak" becomes "with" or "through" in your sentences. How does English name a method?',why:'A method is "by + -ing": by using this construction.',
 items:[Y('03.10','You can say it ___ using this construction.','by'),Y('29.09','Look at it ___ using Gemini.','by')]},
{k:'basis',sec:'prep',label:'on a … basis',tr:'gerçek zamanlı bazda (-da)',wrong:['in','∅'],thin:true,
 trap:'"Bazda" (-da) gives "in".',why:'"On a remote basis", "on a daily basis", "on a real-time basis".',
 items:[Y('01.10','They work ___ a remote basis.','on'),Y('24.09','We update it ___ a real-time basis.','on')]},
{k:'struggle_to',sec:'prep',label:'struggle to / interested in -ing',tr:'no Turkish source recorded',wrong:['for','in to'],thin:true,
 trap:'Check what form the verb takes after this word.',why:'"Struggle to do something", and "interested in doing something".',
 items:[Y('28.09','I have been struggling ___ increase my automaticity.','to'),Y('20.09','He might be interested ___ buying our horse.','in')]},
{k:'in_form',sec:'prep',label:'in its original form',tr:'orijinal halleriyle (-le)',wrong:['with'],thin:true,
 trap:'"-le" gives "with".',why:'"In its original form", "in its current form".',
 items:[Y('28.09','Keep them ___ their original form.','in'),N('I like the essay ___ its current form.','in')]},
// ---------- Verb + noun ----------
{k:'vn_decision',sec:'vn',label:'make a decision',tr:'karar vermek',wrong:['give','do'],
 trap:'"Karar vermek" uses "vermek" (give). English uses a different light verb.',
 why:'"Make a decision", "make a choice", "make a selection".',
 items:[Y('20.09','Let her ___ her own decision.','make'),Y('01.10','We ___ our selection yesterday.','made',['did','gave']),N('I need to ___ a decision by Friday.','make')]},
{k:'vn_break',sec:'vn',label:'take a break',tr:'mola vermek',wrong:['give','make'],thin:true,
 trap:'"Mola vermek" uses "vermek" (give).',why:'"Take a break", "take a rest".',
 items:[Y('22.09','Maybe I could ___ a break.','take'),N('Let’s ___ a five-minute break.','take')]},
{k:'vn_analysis',sec:'vn',label:'do an analysis / do research',tr:'analiz yapmak / araştırma yapmak',wrong:['make'],
 trap:'"Yapmak" covers make and do. Which one fits work and tasks?',
 why:'Work and tasks use "do": do an analysis, do some research. ("Run an analysis" also works.)',
 items:[Y('06.10','Can you ___ a thorough analysis?','do|run'),Y('23.09','I ___ some quick research.','did',['made']),N('She’s ___ research on sleep.','doing',['making'])]},
{k:'vn_score',sec:'vn',label:'get a score',tr:'skor yapmak',wrong:['make'],thin:true,
 trap:'"Skor yapmak" uses "yapmak". English uses another verb for results.',why:'"Get a score" or simply "score": she scored 85.',
 items:[Y('06.10','If she ___ a certain score, she qualifies.','gets',['makes']),N('He ___ a high score on the test.','got',['made'])]},
{k:'have_a_talk',sec:'vn',label:'have a talk / conversation',tr:'konuşma yapmak',wrong:['make','do'],
 trap:'"Konuşma yapmak" uses "yapmak". Conversations use another light verb.',
 why:'"Have a talk", "have a conversation", "have a chat".',
 items:[Y('20.09','I need to ___ this talk with Shahin.','have'),Y('20.09','It’s not a good time to ___ this conversation.','have'),N('We ___ a long chat last night.','had',['made','did'])]},
{k:'do_practice',sec:'vn',label:'do practice / exercises',tr:'pratik yapmak / egzersiz yapmak',wrong:['make'],
 trap:'"Pratik yapmak" uses "yapmak". Which English verb fits exercises?',
 why:'"Do some practice", "do exercises", or just "practise".',
 items:[Y('22.09','I’m reluctant to ___ any speaking practice.','do'),Y('05.10','Let’s ___ some shadowing practice.','do'),N('She ___ her exercises every morning.','does',['makes'])]},
{k:'lift_mood',sec:'vn',label:'lift / boost my mood',tr:'moral yükseltmek',wrong:['increase'],
 trap:'"Moral yükseltmek" suggests "increase". Moods go up with another verb.',
 why:'"Lift my mood" or "boost my mood". When it goes the other way: "I feel down".',
 items:[Y('25.09','It really helps to ___ my mood.','lift|boost'),N('Music always ___ my mood.','lifts|boosts',['increases'])]},
{k:'throw_question',sec:'vn',label:'ask a question / float an idea',tr:'ortaya atmak',wrong:['throw'],
 trap:'"Ortaya atmak" suggests "throw". English uses other verbs for questions and ideas.',
 why:'"Ask a question", "float an idea", "put it to them". "Fire away" means "go ahead and ask".',
 items:[Y('30.09','Maybe I can ___ this idea to them.','float|put'),Y('29.09','Go ahead, ___ away!','fire'),N('Can I ___ you a question?','ask')]},
{k:'put_add',sec:'vn',label:'add / set (not "put")',tr:'koymak',wrong:['put','putting'],
 trap:'"Koymak" suggests "put". Columns, buttons and criteria use other verbs.',
 why:'You "add" a column or a button and "set" criteria. "Put" is for placing physical things.',
 items:[Y('23.09','You can do it by ___ a new column.','adding'),Y('23.09','You need to ___ some criteria.','set|establish'),Y('28.09','Let’s ___ a "show more" button.','add')]},
{k:'vn_call',sec:'vn',label:'take a call',tr:'aramayı almak',wrong:['receive'],thin:true,
 trap:'"Almak" suggests "receive".',why:'You "take a call" or "answer a call".',
 items:[Y('06.10','I had to ___ a call from Serkan.','take|answer'),N('Sorry, I need to ___ this call.','take|answer')]},
{k:'vn_meeting',sec:'vn',label:'have / hold a meeting',tr:'toplantı yapmak',wrong:['do','make'],thin:true,
 trap:'"Toplantı yapmak" uses "yapmak".',why:'"Have a meeting" or, more formally, "hold a meeting".',
 items:[Y('29.09','We will ___ a meeting in person.','have|hold'),N('They ___ a meeting every Monday.','have|hold')]}
];
// ---------- Extra new-context items (so sessions can run 50% your sentences / 50% new contexts) ----------
const EXTRA={
of_not_for:[N('He has a deep knowledge ___ local tax rules.','of'),N('Can you give me an example ___ a phrasal verb with "up"?','of'),N('The chances ___ rain tomorrow are low.','of'),N('There is a growing awareness ___ climate risk in banking.','of'),N('This exam is a real test ___ your patience.','of')],
no_prep_verbs:[N('Would you like to join ___ us for dinner?','∅'),N('A stranger approached ___ me at the station.','∅'),N('Please reply ___ this email by Friday.','to',['∅','with'],'"Reply" is the exception: it needs "to".'),N('The auditors will contact ___ you next week.','∅')],
add_to:[N('Add a pinch of salt ___ the soup.','to'),N('Please add my name ___ the guest list.','to'),N('Save the file ___ the shared folder.','to'),N('I added a few notes ___ the report.','to')],
on_my_list:[N('Milk is ___ my shopping list.','on'),N('Is fish ___ the menu tonight?','on'),N('Visiting Japan is high ___ my bucket list.','on')],
include_in:[N('Are drinks included ___ the package?','in'),N('She wasn’t involved ___ the decision.','in'),N('Please keep me ___ the loop.','in')],
move_on_to:[N('Let’s move ___ the budget figures now.','on to'),N('After the introduction, the teacher moved ___ the main topic.','on to')],
dedicate_to:[N('He dedicated his life ___ teaching.','to'),N('We are fully committed ___ the project.','to')],
these_days:[N('Everyone seems so busy ___ these days.','∅'),N('What are you reading ___ these days?','∅'),N('Kids grow up so fast ___ these days.','∅')],
over_time:[N('Prices have risen steadily ___ time.','over'),N('The colours faded gradually ___ time.','over'),N('Our team has changed a lot ___ time.','over')],
weekends:[N('The office is closed ___ weekends.','at|on'),N('We usually visit my parents ___ the weekend.','at|on|over'),N('Shops get very busy ___ weekends.','at|on')],
dates_times:[N('The meeting is ___ Monday morning.','on'),N('My flight leaves ___ 6:45.','at'),N('We got married ___ 2012.','in',['on','at'],'Years take "in".'),N('I always feel sleepy ___ the afternoon.','in',['at','on'],'Parts of the day take "in", except "at night".'),N('The report is due ___ 15 November.','on')],
begin_lastmin:[N('He always arrives ___ the last minute.','at'),N('There is a summary ___ the end of each chapter.','at')],
time_duration:[N('I’ve lived in Istanbul ___ ten years.','for',['since']),N('He has worked here ___ 2019.','since',['for'])],
sense_of:[N('She has a great sense ___ humour.','of'),N('What are the advantages ___ this plan?','of'),N('There’s something wrong ___ my laptop.','with',['about','of'])],
confused_about:[N('I’m really excited ___ the trip.','about'),N('She was worried ___ the results.','about'),N('Don’t be so negative ___ everything.','about')],
same_about:[N('I could say the same ___ my brother.','about')],
same_as:[N('Her dress is the same colour ___ mine.','as'),N('This year’s budget is the same ___ last year’s.','as')],
for_me:[N('This chair is too low ___ me.','for'),N('It’s difficult ___ him to say no.','for'),N('This idea is completely new ___ me.','to',['for'],'"New to me" means I haven’t met it before.'),N('Running every day is good ___ your health.','for')],
ask_sb_q:[N('Thanks for sharing your story ___ us.','with',['to']),N('I’ll share the slides ___ the team.','with',['to']),N('Here’s a question ___ you: why did you choose finance?','for',['to'])],
no_point_in:[N('There’s no point ___ arguing with him.','in'),N('Is there any point ___ calling them again?','in')],
mention_discuss:[N('Did she mention ___ the price?','∅'),N('Let’s discuss ___ the plan over lunch.','∅'),N('Can you tell me ___ your weekend?','about',['∅'],'"Tell someone about" does take "about".')],
rooted_in:[N('The tradition is rooted ___ Ottoman history.','in'),N('The film is based ___ a true story.','on',['to']),N('Most of the delays stem ___ one bad decision.','from',['by'])],
responsible_for:[N('Who is responsible ___ the budget?','for'),N('It’s up ___ you to decide.','to',['on'])],
against:[N('Most people voted against ___ the plan.','∅'),N('Lean your bike against ___ the wall.','∅')],
seek_chase:[N('Many young people are seeking ___ jobs abroad.','∅'),N('I’m searching ___ my keys.','for',['∅'],'"Search for" does take "for".')],
invest_in:[N('They invested heavily ___ property.','in'),N('I put a lot of time ___ learning English.','into'),N('You should invest ___ a good pair of shoes.','in'),N('If you put ___ the hours, you’ll see results.','in',['∅','into'],'"Put in the hours" with nothing after it uses "in".')],
swap_for:[N('Can I swap this shirt ___ a bigger size?','for'),N('We replaced the old printer ___ a new one.','with',['for'])],
limit_to:[N('Please limit your talk ___ ten minutes.','to'),N('Each guest is limited ___ two drinks.','to'),N('There’s no limit ___ what you can learn.','to',['for']),N('Let’s keep the list limited ___ five items.','to',['with'])],
key_to:[N('Patience is the key ___ good parenting.','to'),N('Nobody knows the answer ___ that question.','to')],
leave_out_of:[N('Please leave me ___ this argument.','out of'),N('Let’s set this issue ___ until next week.','aside',['out']),N('He was left ___ the team photo.','out of')],
on_device:[N('Is this film ___ Netflix?','on'),N('I found it ___ their website.','on'),N('She spends hours ___ her tablet.','on'),N('We stayed ___ a small Greek island.','on')],
on_trip_leave:[N('She’s ___ maternity leave until March.','on'),N('He’s away ___ business this week.','on')],
angry_with:[N('Don’t be angry ___ me.','with',['to']),N('She got mad ___ the referee.','at',['with']),N('I’m tired ___ waiting.','of',['from']),N('My daughter is very close ___ her grandmother.','to',['with']),N('We were all shocked ___ the news.','by|at',['from'])],
good_at:[N('I’m not very good ___ remembering names.','at'),N('She’s getting better ___ tennis.','at')],
save_for:[N('Let’s save the dessert ___ later.','for'),N('Keep some energy ___ the second half.','for')],
remind_of:[N('This song reminds me ___ my school days.','of'),N('You remind me ___ your father.','of')],
been_to:[N('She has never been ___ London.','to'),N('Have you been ___ the new shopping centre yet?','to')],
specific_to:[N('This problem isn’t specific ___ Turkey.','to')],
pace_at:[N('Walk ___ your own pace.','at')],
superior_to:[N('This hotel is superior ___ the one we stayed in last year.','to')],
different_from:[N('My job is very different ___ yours.','from|to',['than']),N('Life in Dubai is different ___ life in Istanbul.','from|to',['than'])],
accused_of:[N('They were accused ___ cheating.','of')],
get_used_to:[N('You’ll soon get used ___ the noise.','to')],
worth_ing:[N('Istanbul is worth ___ (visit) in spring.','visiting',['to visit'])],
short_on_time:[N('Sorry, I’m a bit short ___ time today.','on')],
congratulate_on:[N('We congratulated them ___ their wedding.','on')],
scene:[N('A new band burst ___ the music scene last year.','onto|on',['into'])],
help_with:[N('Could you help me ___ this form?','with')],
wait_for:[N('Wait ___ me, I’m coming!','for')],
insist_on:[N('He insisted ___ driving me home.','on')],
resonate_with:[N('His speech really resonated ___ young voters.','with'),N('That idea doesn’t resonate ___ me.','with')],
paste_into:[N('Copy the text and paste it ___ an email.','into')],
come_across_as:[N('He comes across ___ very confident.','as'),N('I didn’t mean to come across ___ rude.','as')],
by_using:[N('You can save time ___ using shortcuts.','by'),N('She learned English ___ watching films.','by')],
basis:[N('We meet ___ a weekly basis.','on'),N('Staff are paid ___ a monthly basis.','on')],
struggle_to:[N('Many students struggle ___ concentrate in the afternoon.','to'),N('Are you interested ___ joining our team?','in')],
in_form:[N('The document is only available ___ PDF form.','in')],
vn_decision:[N('It’s time to ___ a choice.','make')],
vn_break:[N('You look tired. Why don’t you ___ a rest?','take|have')],
vn_analysis:[N('We need to ___ more research before we decide.','do')],
vn_score:[N('She ___ 90 out of 100 in the exam.','scored|got',['made'])],
have_a_talk:[N('Let’s ___ a quick chat after lunch.','have')],
do_practice:[N('I ___ some stretching exercises before work.','do')],
lift_mood:[N('A sunny day can really ___ your mood.','lift|boost',['increase'])],
throw_question:[N('He ___ the idea of a four-day week at the meeting.','floated|raised|suggested',['threw'])],
put_add:[N('Can you ___ a new column for the dates?','add'),N('We need to ___ clear rules for the team.','set|establish')],
vn_call:[N('She couldn’t ___ my call because she was driving.','take|answer',['receive'])],
vn_meeting:[N('We’ll ___ a meeting to discuss it.','have|hold',['do','make'])]
};
BANK.forEach(p=>{if(EXTRA[p.k])p.items.push(...EXTRA[p.k]);});
// ---------- Contrast pairs: two sentences, same gap, different answers ----------
function C(t1,a1,t2,a2,n){return{s:'n',c:true,t:t1,a:a1,t2,a2,n};}
const PAIRS={
over_time:[C('We got there just ___ time for the start.','in','Prices have risen steadily ___ time.','over','"In time" = early enough; "over time" = gradually.')],
begin_lastmin:[C('We met ___ the beginning of the session.','at','___ the beginning, everything felt confusing.','in','"At the beginning of X" is a point; "In the beginning" (no "of") means "at first".')],
these_days:[C('I’m really busy ___ these days.','∅','Life was harder back ___ those days.','in','"These days" takes nothing; "in those days" talks about the past.')],
been_to:[C('I’ve been ___ Dubai twice.','to','I’ve been ___ Dubai for three days now.','in','"Been to" = visited; "been in" = staying there for a period.')],
same_about:[C('I can say the same ___ my sister.','about','The same goes ___ my sister.','for','"Say the same about" vs the fixed phrase "the same goes for".')],
remind_of:[C('This place reminds me ___ my childhood.','of','Remind me ___ call the bank tomorrow.','to','"Remind someone of a thing" vs "remind someone to do something".')],
no_prep_verbs:[C('Please contact ___ me by Friday.','∅','Please reply ___ me by Friday.','to','"Contact" takes its object directly; "reply" needs "to".')],
mention_discuss:[C('We discussed ___ the plan for an hour.','∅','We talked ___ the plan for an hour.','about','"Discuss" takes its object directly; "talk" needs "about".')],
seek_chase:[C('They are seeking ___ a solution.','∅','They are looking ___ a solution.','for','"Seek" takes its object directly; "look" needs "for".')],
swap_for:[C('I swapped tea ___ coffee.','for','I replaced tea ___ coffee.','with','"Swap X for Y" and "replace X with Y" mean the same change.')],
angry_with:[C('I’m angry ___ him.','with','I’m angry ___ the delay.','about','"Angry with" a person, "angry about" a situation.')],
for_me:[C('This topic is completely new ___ me.','to','This topic is really hard ___ me.','for','"New to me" (I haven’t met it) vs "hard for me" (it affects me).')],
time_duration:[C('I’ve worked here ___ 2019.','since','I’ve worked here ___ six years.','for','"Since" + a starting point; "for" + a length of time.')],
dates_times:[C('See you ___ Friday.','on','See you ___ 5 pm.','at','Days take "on"; clock times take "at".'),C('I can’t sleep ___ night.','at','I work best ___ the morning.','in','"At night" is the exception; other parts of the day take "in".')],
move_on_to:[C('Let’s move ___ the next point.','on to','Next month we’re moving ___ a bigger flat.','into','"Move on to" a topic; "move into" a place.')],
add_to:[C('Please add it ___ the list.','to','Please include it ___ the list.','in','"Add to" but "include in".')],
good_at:[C('She’s really good ___ tennis.','at','She’s really good ___ children.','with','"Good at" a skill; "good with" people or tools.')]
};
BANK.forEach(p=>{if(PAIRS[p.k])p.items.push(...PAIRS[p.k]);});
