// ---------- Challenge tab: harder prepositions (sec 'adv'). gen:true = Turkish link is a general mapping, not from the ledger ----------
const ADV=[
// Path and movement
{k:'adv_through',sec:'adv',fam:'path',label:'through',tr:'-den geçerek / aracılığıyla (yours: "through using" for "by using")',wrong:['across','along'],
 trap:'Think of going in one side and out the other, or of a channel something passes through.',
 why:'"Through" = in one side and out the other (through the tunnel), from start to end (through the night), or by means of a person or channel (through a friend). A method with -ing takes "by": by using Gemini.',
 items:[N('We drove ___ the tunnel.','through'),N('I read ___ the contract twice.','through'),N('The light came in ___ the window.','through',['across','from']),
 N('We got the job ___ a friend.','through',['by','with'],'"Through" a person or channel = by means of them.'),N('He worked ___ the night to finish it.','through'),
 Y('29.09','Look at it ___ using Gemini.','by',['through','with'],'A method with -ing takes "by", not "through".')]},
{k:'adv_across',sec:'adv',fam:'path',label:'across',tr:'karşısında / karşıya',gen:true,wrong:['through','along'],
 trap:'Think of a flat surface or a line you go from one side of to the other.',
 why:'"Across" = from one side to the other of a surface or line (across the street, across the river), or in every part of something (across all sectors).',
 items:[N('There’s a café just ___ the street.','across'),N('She swam ___ the river.','across'),N('Prices rose ___ all sectors.','across',['through','along'],'"Across" = in every part of.'),N('I came ___ an old photo yesterday.','across',['through','along'],'"Come across" = find by chance.')]},
{k:'adv_along',sec:'adv',fam:'path',label:'along / during',tr:'boyunca (one word for space and time)',wrong:['through','across'],
 trap:'Turkish "boyunca" covers both space and time. English splits them.',
 why:'"Along" follows a line in space: along the beach, along the road. For a stretch of time, use "during" or "throughout": during the week.',
 items:[N('We walked ___ the beach.','along'),N('There are trees ___ the road.','along'),N('I’ll bring a friend ___.','along',['with','together'],'"Bring someone along" = take them with you.'),
 Y('05.10','I’ll be busy ___ the week.','during|throughout',['along'],'"Along" is for space. For time, use "during" or "throughout".')]},
{k:'adv_towards',sec:'adv',fam:'path',label:'towards vs to',tr:'-e doğru / -e karşı',wrong:['towards'],
 trap:'Turkish "-e karşı / -e doğru" pulls you to "towards". Does the thing arrive at its target or join it?',
 why:'"Towards" = in the direction of (walk towards the door) or about feelings (attitude towards). When something reaches or joins a target, English uses "to": delegate to, link to.',
 items:[Y('29.09','I’m delegating these tasks ___ my team members.','to'),Y('05.10','Let’s link this holiday ___ the weekend.','to'),
 Y('23.09','I need to go easy ___ myself.','on',['towards'],'"Go easy on someone" is a fixed phrase.'),Y('28.09','My parents have a soft spot ___ me.','for',['towards'],'"A soft spot for someone" is a fixed phrase.'),
 N('He walked slowly ___ the door.','towards|toward',['to'],'Moving in that direction, not arriving yet: "towards".'),N('Her attitude ___ work has changed.','towards|to',['for','against'],'Attitudes and feelings: "towards" (British English also says "to").')]},
{k:'adv_beyond',sec:'adv',fam:'path',label:'beyond',tr:'ötesinde',gen:true,wrong:['over','after'],
 trap:'Think of something further than a limit.',
 why:'"Beyond" = further than a place or a limit: beyond that hill, beyond my control, "it’s beyond me" (I can’t understand it).',
 items:[N('The village is just ___ that hill.','beyond',['over','after']),N('Sorry, the delay is ___ our control.','beyond|out of',['over','above']),
 N('That’s ___ me. I just don’t understand it.','beyond',['over','above'],'"It’s beyond me" = I can’t understand it.')]},
{k:'adv_throughout',sec:'adv',fam:'path',label:'throughout',tr:'boyunca',gen:true,wrong:['along'],
 trap:'From the start to the end, or in every part.',
 why:'"Throughout" = during the whole time (throughout the day) or in every part of a place (throughout the country).',
 items:[N('It rained ___ the day.','throughout|all through',['along']),N('The song is famous ___ the country.','throughout|across|all over',['along']),N('She smiled ___ the whole meeting.','throughout|all through',['along'])]},
// Multi-word prepositions
{k:'adv_out_of',sec:'adv',fam:'multi',label:'out of',tr:'-den dışarı (yours: "out from")',wrong:['out from','from'],
 trap:'English uses a fixed two-word pair here, never "out from".',
 why:'"Out of" = leaving the inside of something (ran out of the room), having none left (out of milk), proportions (three out of ten). Never "out from".',
 items:[N('She ran ___ the room.','out of'),N('We’ve run ___ milk.','out of'),N('Three ___ ten people said yes.','out of',['from','in'],'Proportions: "three out of ten".'),
 N('Stay ___ trouble!','out of',['away','from']),Y('01.10','Please keep it ___ the analysis.','out of')]},
{k:'adv_instead_of',sec:'adv',fam:'multi',label:'instead of',tr:'yerine',gen:true,wrong:['instead','rather'],
 trap:'Two words, and the verb after it takes -ing.',
 why:'"Instead of" + noun or -ing: tea instead of coffee, walk instead of taking a taxi.',
 items:[N('Can I have tea ___ coffee?','instead of'),N('Let’s walk ___ taking a taxi.','instead of',['instead','rather'],'"Instead of" + -ing.')]},
{k:'adv_apart_except',sec:'adv',fam:'multi',label:'apart from / except for',tr:'dışında / hariç',gen:true,wrong:['without','despite'],
 trap:'You are leaving one thing out of a group.',
 why:'"Apart from" and "except (for)" leave one thing out: everyone except Ali; apart from the weather, it was perfect.',
 items:[N('Everyone came ___ Ali.','except|apart from|except for',['without']),N('___ the weather, the trip was perfect.','Apart from|Except for',['Without','Despite'])]},
{k:'adv_due_to',sec:'adv',fam:'multi',label:'due to / because of',tr:'yüzünden / nedeniyle',gen:true,wrong:['because','for'],
 trap:'A noun follows, not a full clause.',
 why:'"Due to" and "because of" + noun: cancelled due to the storm. "Because" needs a clause: because it was stormy.',
 items:[N('The flight was cancelled ___ the storm.','due to|because of',['because','for'],'"Because" needs a full clause.'),N('The delay was ___ a technical problem.','due to|because of',['because','for']),
 N('Many people stayed home ___ the snow.','because of|due to',['because'])]},
{k:'adv_according_to',sec:'adv',fam:'multi',label:'according to',tr:'-e göre',gen:true,wrong:['regarding','due to'],
 trap:'It names the source of information, or the plan you follow.',
 why:'"According to" names a source (according to the forecast) or a plan (everything went according to plan).',
 items:[N('___ the forecast, it will rain tomorrow.','According to',['Regarding','Due to']),N('Everything went ___ plan.','according to',['as','by'],'"Go according to plan" is fixed.')]},
{k:'adv_in_terms_of',sec:'adv',fam:'multi',label:'in terms of',tr:'açısından (your ledger has "in these terms" as a calque)',wrong:['in these terms','according to'],
 trap:'"Açısından" becomes a fixed English phrase here.',
 why:'"In terms of" = when we talk about this aspect: in terms of salary, the new job is better.',
 items:[N('___ salary, the new job is better.','In terms of',['In these terms','According to']),N('The project was a success ___ sales.','in terms of',['according to','due to'])]},
{k:'adv_on_behalf_of',sec:'adv',fam:'multi',label:'on behalf of',tr:'adına',gen:true,wrong:['in the name of','for the sake of'],
 trap:'"Adına" tempts a word-for-word "in the name of".',
 why:'"On behalf of" = representing someone: I’m writing on behalf of my company. "In the name of" sounds religious or legal.',
 items:[N('I’m writing ___ my company.','on behalf of'),N('She accepted the award ___ her team.','on behalf of')]},
{k:'adv_despite',sec:'adv',fam:'multi',label:'despite / in spite of',tr:'-e rağmen',gen:true,wrong:['although','even though'],
 trap:'A noun or -ing follows, not a full clause.',
 why:'"Despite" and "in spite of" + noun or -ing: despite the rain, despite being tired. "Although" needs a full clause. Never "despite of".',
 items:[N('We went out ___ the rain.','despite|in spite of',['although','even']),N('___ being tired, she finished the report.','Despite|In spite of',['Although','Even though'],'"Despite" + -ing.'),N('He failed, ___ all his efforts.','despite|in spite of',['although'])]},
{k:'adv_regardless_of',sec:'adv',fam:'multi',label:'regardless of',tr:'-e bakmaksızın',gen:true,wrong:['regardless','despite of'],
 trap:'Two words; it means "it doesn’t matter what".',
 why:'"Regardless of" = it does not matter: everyone pays the same, regardless of age.',
 items:[N('Everyone pays the same, ___ age.','regardless of'),N('The rule applies to everyone, ___ their position.','regardless of')]},
{k:'adv_as_for',sec:'adv',fam:'multi',label:'as for',tr:'-e gelince',wrong:['for','about'],
 trap:'You are turning to a new topic.',
 why:'"As for X" turns to a new topic: as for the weather, it’s another story.',
 items:[Y('03.10','___ the feedback you gave, I agree with most of it.','As for',['For','About']),N('I love the city. ___ the weather, that’s another story.','As for',['For','About'])]},
{k:'adv_prior_to',sec:'adv',fam:'multi',label:'prior to',tr:'-den önce',gen:true,wrong:['prior','ago'],
 trap:'A formal word for "before" needs its partner.',
 why:'"Prior to" is a formal "before": prior to joining us. "Prior" alone is an adjective.',
 items:[N('Please arrive 30 minutes ___ the meeting.','prior to|before',['prior','ago']),N('___ joining us, she worked in a bank.','Prior to|Before',['Prior','Ago'])]},
// Position and relation
{k:'adv_among_between',sec:'adv',fam:'position',label:'among / between / from',tr:'arasında (one word for both)',wrong:['among','between'],
 trap:'Turkish "arasında" covers both. Two clear items, or a group? Or are you choosing out of a group?',
 why:'"Between" two (or clearly separate) things; "among" a group; choosing out of a group is "from": pick three from the list.',
 items:[Y('28.09','Pick three items ___ the phrasal verbs.','from',['among','between'],'Choosing out of a group: "from".'),N('She was ___ the first to arrive.','among',['between']),
 N('The house is ___ the bank and the school.','between',['among']),N('There’s a lot of stress ___ students.','among',['between']),N('Let’s split the bill ___ the two of us.','between',['among'])]},
{k:'adv_within',sec:'adv',fam:'position',label:'within',tr:'içinde',gen:true,wrong:['in','inside'],
 trap:'Inside a limit of time, money or distance.',
 why:'"Within" = inside a limit: within 24 hours (no later than), within budget, within walking distance. "In 24 hours" means after 24 hours.',
 items:[N('We’ll reply ___ 24 hours.','within',['inside'],'"Within" = no later than.'),N('Please try to stay ___ budget.','within',['inside','in']),N('Is the hotel ___ walking distance?','within',['in','inside'])]},
{k:'adv_below',sec:'adv',fam:'position',label:'below / under / beneath',tr:'altında',gen:true,wrong:['below','beneath'],
 trap:'Is this a position, or a level on a scale?',
 why:'"Under" (or "beneath") for position: hiding under the bed. "Below" for levels and numbers: below zero, below average.',
 items:[N('The cat is hiding ___ the bed.','under|beneath|underneath',['below']),N('The temperature fell ___ zero last night.','below',['beneath'],'Levels and numbers: "below".')]},
{k:'adv_alongside',sec:'adv',fam:'position',label:'alongside',tr:'yanında / ile birlikte',gen:true,wrong:['along'],
 trap:'Next to, or together with.',
 why:'"Alongside" = next to, or together with: she works alongside her husband. "Along" is for following a line.',
 items:[N('She works ___ her husband in the shop.','alongside|with',['along']),N('The new rules will run ___ the old ones for a year.','alongside',['along'])]},
{k:'adv_amid',sec:'adv',fam:'position',label:'amid',tr:'ortasında',gen:true,wrong:['among','between'],
 trap:'In the middle of a situation (news style).',
 why:'"Amid" = in the middle of a situation, mostly in news and formal writing: shares fell amid fears of a recession.',
 items:[N('The shares fell ___ fears of a recession.','amid|amidst',['among','between'],'"Amid" goes with situations; "among" with groups of people or things.'),N('He stayed calm ___ the chaos.','amid|in',['among'])]},
{k:'adv_upon',sec:'adv',fam:'position',label:'upon / on arrival',tr:'-ince / üzerine',gen:true,wrong:['at','in'],
 trap:'A formal way to say "when this happens".',
 why:'"On" or "upon" + noun = when it happens: on arrival, upon receipt. "Once upon a time" is fixed.',
 items:[N('___ arrival, please check in at reception.','On|Upon',['At','In'],'"On arrival" = when you arrive.'),N('Once ___ a time, there was a king.','upon',['on','in'],'A fixed phrase in stories.')]},
{k:'adv_above_level',sec:'adv',fam:'position',label:'above a level',tr:'belli bir seviyeden sonra',wrong:['after','over'],
 trap:'Turkish "-den sonra" gives "after". Is this about time, or about a level?',
 why:'Levels and amounts take "above": above a certain level, above average. "After" is for time.',
 items:[Y('06.10','___ a certain level, the questions get much harder.','Above|Beyond',['After']),N('His results are well ___ average.','above',['over','after'])]}
];
const ADV_FAMILIES=[
 {id:'path',label:'Path and movement',keys:['adv_through','adv_across','adv_along','adv_towards','adv_beyond','adv_throughout']},
 {id:'multi',label:'Multi-word prepositions',keys:['adv_out_of','adv_instead_of','adv_apart_except','adv_due_to','adv_according_to','adv_in_terms_of','adv_on_behalf_of','adv_despite','adv_regardless_of','adv_as_for','adv_prior_to']},
 {id:'position',label:'Position and relation',keys:['adv_among_between','adv_within','adv_below','adv_alongside','adv_amid','adv_upon','adv_above_level']}];
ADV.forEach(p=>BANK.push(p));
// Contrast-pair hints (level 1) for both sentences
const PAIR_HINTS={over_time:'A is about being early enough; B is about gradual change.',begin_lastmin:'A has "of the session" after it; B stands alone and means "at first".',
these_days:'A is about now; B is about the past.',been_to:'A counts visits; B is about staying there right now.',same_about:'A follows "say the same"; B follows "the same goes".',
remind_of:'A is followed by a thing; B by a verb.',no_prep_verbs:'Look at the verbs: "contact" in A, "reply" in B.',mention_discuss:'Look at the verbs: "discuss" in A, "talk" in B.',
seek_chase:'Look at the verbs: "seek" in A, "look" in B.',swap_for:'Look at the verbs: "swap" in A, "replace" in B.',angry_with:'A is about a person; B is about a situation.',
for_me:'A: something you haven’t met before. B: something that is difficult for you.',time_duration:'A gives a starting point; B gives a length of time.',
add_to:'Look at the verbs: "add" in A, "include" in B.',good_at:'A is a skill; B is about people.',move_on_to:'A is a topic; B is a place.'};
const PAIR_HINTS_2={dates_times:['A is a day; B is a clock time.','A is night-time; B is a part of the day.']};
